SongRequest.WebFrontEndService/Models/Feedback.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SongRequest.WebFrontEndService.Models
{
    public enum FeedbackLevel
    {
        Info,
        Warning,
        Error
    }

    public class Feedback
    {
        public FeedbackLevel Level { get; set; }
        public string Message { get; set; }

        public Feedback() { }

        public Feedback(FeedbackLevel level, string message)
        {
            this.Level = level;
            this.Message = message;
        }

        public string GetDisplayClass()
        {
            switch(this.Level)
            {
                case FeedbackLevel.Error:
                    return "alert alert-danger";
                case FeedbackLevel.Warning:
                    return "alert alert-warning";
                case FeedbackLevel.Info:
                default:
                    return "alert alert-dark";
            }
        }
    }
}

SongRequest.WebFrontEndService/Models/RequestedSong.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SongRequest.WebFrontEndService.Models
{
    public class RequestedSong
    {
        public string Artist { get; set; }

        public string Title { get; set; }

        public int NumRequests { get; set; }
    }
}

SongRequest.WebFrontEndService/Models/SongRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SongRequest.WebFrontEndService.Models
{
    public enum GenreOptions
    {
        Alternative,
        Classical,
        Country,
        [Display(Name = "Hip Hop / R&B")]
        HipHop,
        Jazz,
        Pop,
        Rap,
        Rock
    }

    public class SongRequest
    {
        [Required]
        public string Artist { get; set; }

        [Required]
        public string Title { get; set; }

        public GenreOptions Genre { get; set; }
    }
}

SongRequest.WebFrontEndService/Models/SongRequestForDisplay.cs
using System;

namespace SongRequest.WebFrontEndService.Models
{
    public class SongRequestForDisplay
    {
        public string Artist { get; set; }

        public string Title { get; set; }

        public string Genre { get; set; }

        public DateTimeOffset RequestDate { get; set; }
    }
}

SongRequest.WebFrontEndService/Pages/Data.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using SongRequest.WebFrontEndService.Models;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;

namespace SongRequest.WebFrontEndService.Pages
{
    public class DataModel : PageModel
    {
        [BindProperty]
        public IEnumerable<SongRequestForDisplay> SongRequests { get; set; }

        [BindProperty]
        public IEnumerable<RequestedSong> RequestedSongs { get; set; }

        [BindProperty]
        public Feedback Feedback { get; set; }

        private readonly HttpClient _httpClient;

        public DataModel(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public async Task OnGetAsync()
        {
            await FetchData();
        }

        public async Task<IActionResult> OnPostRefreshAsync()
        {
            await FetchData();
            return Page();
        }

        private async Task FetchData()
        {
            var result = await _httpClient.GetAsync($"{Environment.GetEnvironmentVariable("SONGREQUEST_APISERVICE_BASE_URL")}api/SongRequests?top=20");
            if (result.IsSuccessStatusCode)
            {
                var content = await result.Content.ReadAsStringAsync();
                this.SongRequests = JsonConvert.DeserializeObject<SongRequestForDisplay[]>(content);
            }
            else
            {
                this.Feedback = new Feedback(FeedbackLevel.Warning, "Unable to refresh the data.");
                this.SongRequests = new SongRequestForDisplay[0];
            }

            result = await _httpClient.GetAsync($"{Environment.GetEnvironmentVariable("SONGREQUEST_APISERVICE_BASE_URL")}api/SongRequests/TopRequests");
            if (result.IsSuccessStatusCode)
            {
                var content = await result.Content.ReadAsStringAsync();
                this.RequestedSongs = JsonConvert.DeserializeObject<RequestedSong[]>(content);
            }
            else
            {
                this.Feedback = new Feedback(FeedbackLevel.Warning, "Unable to refresh the data.");
                this.RequestedSongs = new RequestedSong[0];
            }
        }
    }
}

SongRequest.WebFrontEndService/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SongRequest.WebFrontEndService.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SongRequest.WebFrontEndService/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SongRequest.WebFrontEndService.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

SongRequest.WebFrontEndService/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SongRequest.WebFrontEndService.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SongRequest.WebFrontEndService/Pages/Request.cshtml.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using SongRequest.WebFrontEndService.Models;

namespace SongRequest.WebFrontEndService.Pages
{
    public class RequestModel : PageModel
    {
        [BindProperty]
        public Models.SongRequest SongRequest { get; set; }

        [BindProperty]
        public Feedback Feedback { get; set; }

        private HttpClient _httpClient;

        public RequestModel(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                this.Feedback = new Feedback(FeedbackLevel.Error, "Please correct errors below");
                return Page();
            }


            dynamic requestBodyObject = new ExpandoObject();
            requestBodyObject.Artist = this.SongRequest.Artist;
            requestBodyObject.Title = this.SongRequest.Title;
            requestBodyObject.Genre = Enum.GetName(typeof(Models.GenreOptions), this.SongRequest.Genre);
            requestBodyObject.RequestDate = DateTimeOffset.Now;
            var jsonRequestBody = JsonConvert.SerializeObject(requestBodyObject);

            var httpRequest = new HttpRequestMessage(HttpMethod.Post, $"{Environment.GetEnvironmentVariable("SONGREQUEST_APISERVICE_BASE_URL")}api/SongRequests");
            httpRequest.Content = new StringContent(jsonRequestBody, Encoding.UTF8, "application/json");

            var response = await _httpClient.SendAsync(httpRequest);
            if (!response.IsSuccessStatusCode)
            {
                this.Feedback = new Feedback(FeedbackLevel.Error, 
                    $"There was an error sending your request. [{response.StatusCode}: {response.ReasonPhrase}]");
                return Page();
            }

            this.Feedback = new Feedback(FeedbackLevel.Info,
                $"Successfully requested: {JsonConvert.SerializeObject(this.SongRequest, Formatting.Indented)}");

            // Clear form but stay on page
            ModelState.Clear();
            this.SongRequest = null;
            return Page();
        }
    }
}

SongRequest.WebFrontEndService/Pages/Data.cshtml
@page
@model SongRequest.WebFrontEndService.Pages.DataModel
@{
  ViewData["Title"] = "Data";
}

<div class="data-refresh">
  @*<span id="refresh-icon" class="oi oi-reload" title="reload" aria-hidden="true" style="display: none;"></span>*@
  <button id="refresh" type="button" class="btn btn-sm btn-outline-dark" asp-page-handler="refresh">Refresh All Data</button>
</div>


@if (Model.Feedback != null)
{
  <div class="@Model.Feedback.GetDisplayClass()" role="alert">
    @Model.Feedback.Message
  </div>
}

<h1 class="cover-heading">Most recently requested songs</h1>

<table id="latest" class="table table-sm table-responsive-sm">
  <thead class="thead-light">
    <tr>
      <th scope="col">Requested Date</th>
      <th scope="col">Artist</th>
      <th scope="col">Song Title</th>
      <th scope="col">Genre</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var request in Model.SongRequests)
    {
      <tr>
        <td>@request.RequestDate.ToLocalTime().ToString("MM/dd/yyyy hh:mm:ss tt ")</td>
        <td>@request.Artist</td>
        <td>@request.Title</td>
        <td>@request.Genre</td>
      </tr>
    }
  </tbody>
</table>

<h1 class="cover-heading">Top ten most requested songs</h1>

<table id="top" class="table table-sm table-responsive-sm">
  <thead class="thead-light">
    <tr>
      <th scope="col">Artist</th>
      <th scope="col">Song Title</th>
      <th scope="col">Number of Requests</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var song in Model.RequestedSongs)
    {
      <tr>
        <td>@song.Artist</td>
        <td>@song.Title</td>
        <td>@song.NumRequests</td>
      </tr>
    }
  </tbody>
</table>


@section Scripts {
  <script>
    $(document).ready(function () {
      setInterval(function () {
        $.ajax({
          url: `${window.location.protocol}//${window.location.host}/Data?handler=refresh`,
          type: "POST",
          beforeSend: function (request) {
            /*$("#refresh-icon").css("display", "inline-block");*/
            $("#refresh").prop("disabled", true);
            request.setRequestHeader("RequestVerificationToken", "@HttpContext.GetAntiforgeryToken()");
          }
        })
          .done(function (response) {
            let $response = $($.parseHTML(response));
            $("#latest").html($response.find("#latest").html());
            $("#top").html($response.find("#top").html());
          })
          .always(function () { $("#refresh").prop("disabled", false); /*$("#refresh-icon").css("display", "none");*/ });
      }, 10000);
    });
  </script>
}

SongRequest.WebFrontEndService/Pages/Index.cshtml
@page
@model IndexModel
@{
  ViewData["Title"] = "Home";
}

<h1 class="cover-heading">Welcome.</h1>
<p class="lead">Use this service to request a song from any genre, by any artist, to be played by an imaginary nationwide station.</p>
<a asp-page="/Request" class="btn btn-lg btn-secondary">Request a song</a>

SongRequest.WebFrontEndService/Pages/Request.cshtml
@page
@model SongRequest.WebFrontEndService.Pages.RequestModel
@{
  ViewData["Title"] = "Request";
}

<h1 class="cover-heading">Request a song</h1>
<p class="lead">Complete the form below to submit your request. An artist name and song title are required.</p>

@if (Model.Feedback != null)
{
<div class="@Model.Feedback.GetDisplayClass()" role="alert">
  @Model.Feedback.Message
</div>
}

<form method="post">
  <div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-lg">Artist</label>
    <div class="col-sm-10">
      <input asp-for="SongRequest.Artist" class="form-control form-control-lg" />
      <span asp-validation-for="SongRequest.Artist"></span>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-lg">Title</label>
    <div class="col-sm-10">
      <input asp-for="SongRequest.Title" class="form-control form-control-lg" />
      <span asp-validation-for="SongRequest.Title"></span>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label col-form-label-lg">Genre</label>
    <div class="col-sm-10">
      <select asp-for="SongRequest.Genre" class="form-control form-control-lg"
              asp-items="Html.GetEnumSelectList<Models.GenreOptions>()"></select>
    </div>
  </div>
  <button type="submit" class="btn btn-lg btn-dark">Submit</button>
</form>

SongRequest.WebFrontEndService/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - Song Request Service</title>

  <environment include="Development">
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/open-iconic/font/css/open-iconic-bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
  </environment>
  <environment exclude="Development">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"
          asp-fallback-href="~/lib/twitter-bootstrap/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" 
          integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous"
          asp-fallback-href="~/lib/open-iconic/font/css/open-iconic-bootstrap.min.css"
          asp-fallback-test-class="oi" asp-fallback-test-property="font-family" asp-fallback-test-value="'Icons'"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
  </environment>
</head>

<body class="text-center">

  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column"
    <header class="masthead mb-auto">
      <div class="inner">
        <h3 class="masthead-brand">Song Request Service</h3>
        <nav class="nav nav-masthead justify-content-center">
          <a class="nav-link @(ViewContext.RouteData.Values["Page"].ToString() == "/Index" ? "active" : "")" asp-page="/Index">Home</a>
          <a class="nav-link @(ViewContext.RouteData.Values["Page"].ToString() == "/Request" ? "active" : "")" asp-page="/Request">Request</a>
          <a class="nav-link @(ViewContext.RouteData.Values["Page"].ToString() == "/Data" ? "active" : "")" asp-page="/Data">Data</a>
        </nav>
      </div>
    </header>

    <main role="main" class="inner cover">
      @RenderBody()
    </main>

    <footer class="mastfoot mt-auto">
      <div class="inner">
        <p>&copy; 2018 - Song Request Service</p>
      </div>
    </footer>
  </div>

  <environment include="Development">
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" 
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" 
            crossorigin="anonymous"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
  </environment>
  <environment exclude="Development">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            asp-fallback-src="~/lib/jquery/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" 
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" 
            crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy">
    </script>
    <script src="~/js/site.js" asp-append-version="true"></script>
  </environment>

  @RenderSection("Scripts", required: false)
</body>
</html>